spring.application.name=AIPlanner

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_planner_db
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsASecretKeyForAIPlannerJwtAuthThisIsASecretKey
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

ai.provider=gemini
ai.gemini.api-key=AIzaSyBcJ6gMd6Pkg2oF336jsVpXJ4VZsI_ZCvY
ai.gemini.model=gemini-2.5-flash
ai.gemini.base-url=https://generativelanguage.googleapis.com